export const FETCH_COMMENTS_PENDING = 'FETCH_COMMENTS_PENDING';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

export const FETCH_NEW_COMMENT_PENDING = 'FETCH_NEW_COMMENT_PENDING';
export const FETCH_NEW_COMMENT_ERROR = 'FETCH_NEW_COMMENT_ERROR';
export const FETCH_NEW_COMMET_SUCCESS = 'FETCH_NEW_COMMET_SUCCESS';