export const FETCH_MARKERS_PENDING = 'FETCH_MARKERS_PENDING';
export const FETCH_MARKERS_SUCCESS = 'FETCH_MARKERS_SUCCESS';
export const FETCH_MARKERS_ERROR = 'FETCH_MARKERS_ERROR';
export const FETCH_USER_MARKERS_SUCCESS = 'FETCH_USER_MARKERS_SUCCESS';
export const DELETE_MARKER_SUCCESS = 'DELETE_MARKER_SUCCESS';