export const FETCH_MARKERS_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_MARKERS_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_MARKERS_ERROR = 'FETCH_CATEGORIES_ERROR';
export const FETCH_USER_MARKERS_SUCCESS = 'FETCH_USER_MARKERS_SUCCESS';