export const REG_USER_PENDING = 'REG_USER_PENDING';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_ERROR = 'REG_USER_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';