export const REG_USER_PENDING = 'REG_USER_PENDING';
export const REG_USER_SUCCESS = 'REG_USER_SUCCESS';
export const REG_USER_ERROR = 'REG_USER_ERROR';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_STAYON = 'AUTH_STAYON';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_PENDING = 'AUTH_PENDING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_CHANGE_NAME = 'USER_CHANGE_NAME';
export const USER_CHANGE_AVATAR = 'USER_CHANGE_AVATAR';